# Generated by Django 4.2.4 on 2023-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
